; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = test

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:test]
build_type = debug

lib_deps =
    sensirion/Sensirion I2C SCD4x@^0.4.0
    olikraus/U8g2@^2.35.15
    claws/BH1750@^1.2.0